# implicitly
function_parameter_count: 10
disabled_rules: # rule identifiers to exclude from running
- line_length
- trailing_whitespace
- force_try
- nesting
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
